/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Brayan C
 */
public class PanelGanado extends javax.swing.JPanel {

    /**
     * Creates new form panelGanado
     */
    public PanelGanado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelSideBar1 = new javax.swing.JPanel();
        btnEditarDatos = new javax.swing.JButton();
        btnRegistrarGanado = new javax.swing.JButton();
        jblGanado = new javax.swing.JLabel();
        panelLinea = new javax.swing.JPanel();
        btnListaGanado = new javax.swing.JButton();
        panelVacio = new javax.swing.JPanel();

        background.setBackground(new java.awt.Color(255, 255, 255));

        panelSideBar1.setBackground(new java.awt.Color(35, 52, 78));
        panelSideBar1.setForeground(new java.awt.Color(46, 125, 50));
        panelSideBar1.setPreferredSize(new java.awt.Dimension(270, 892));
        panelSideBar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarDatos.setBackground(new java.awt.Color(55, 72, 95));
        btnEditarDatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-toro-32.png"))); // NOI18N
        btnEditarDatos.setText("Editar datos");
        btnEditarDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnEditarDatos.setBorderPainted(false);
        btnEditarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarDatos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarDatos.setIconTextGap(15);
        panelSideBar1.add(btnEditarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 60));

        btnRegistrarGanado.setBackground(new java.awt.Color(55, 72, 95));
        btnRegistrarGanado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarGanado.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32 (1).png"))); // NOI18N
        btnRegistrarGanado.setText("Registrar ganado");
        btnRegistrarGanado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnRegistrarGanado.setBorderPainted(false);
        btnRegistrarGanado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarGanado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarGanado.setIconTextGap(15);
        panelSideBar1.add(btnRegistrarGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 60));

        jblGanado.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblGanado.setForeground(new java.awt.Color(255, 255, 255));
        jblGanado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-vaca-70.png"))); // NOI18N
        jblGanado.setText("Ganado");
        jblGanado.setIconTextGap(10);
        panelSideBar1.add(jblGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 48, 200, 54));

        panelLinea.setBackground(new java.awt.Color(245, 245, 245));
        panelLinea.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout panelLineaLayout = new javax.swing.GroupLayout(panelLinea);
        panelLinea.setLayout(panelLineaLayout);
        panelLineaLayout.setHorizontalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelLineaLayout.setVerticalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        panelSideBar1.add(panelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 120, 200, 3));

        btnListaGanado.setBackground(new java.awt.Color(55, 72, 95));
        btnListaGanado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListaGanado.setForeground(new java.awt.Color(255, 255, 255));
        btnListaGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32_1.png"))); // NOI18N
        btnListaGanado.setText("Lista de ganado");
        btnListaGanado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnListaGanado.setBorderPainted(false);
        btnListaGanado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaGanado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListaGanado.setIconTextGap(15);
        panelSideBar1.add(btnListaGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 248, 60));

        panelVacio.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSideBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addGap(11, 11, 11))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelVacio() {
        return panelVacio;
    }
    
    public JButton getBtnRegistrarGanado() {
        return btnRegistrarGanado;
    }

    public JButton getBtnEditarDatos() {
        return btnEditarDatos;
    }

    public JButton getBtnListaGanado() {
        return btnListaGanado;
    }
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnListaGanado;
    private javax.swing.JButton btnRegistrarGanado;
    private javax.swing.JLabel jblGanado;
    private javax.swing.JPanel panelLinea;
    private javax.swing.JPanel panelSideBar1;
    private javax.swing.JPanel panelVacio;
    // End of variables declaration//GEN-END:variables
}
