/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Brayan C
 */
public class PanelGanado extends javax.swing.JPanel {

    /**
     * Creates new form panelGanado
     */
    public PanelGanado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelSideBar1 = new javax.swing.JPanel();
        btnFinanzas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnRegistrarGanado = new javax.swing.JButton();
        lblTituloSideBar = new javax.swing.JLabel();
        panelLinea = new javax.swing.JPanel();
        btnHistorialSanitario = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        panelRegistrarGanado = new javax.swing.JPanel();
        jblTituloPanel = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jblFechaNacimiento = new javax.swing.JLabel();
        jcbMes = new javax.swing.JComboBox<>();
        jcbDia = new javax.swing.JComboBox<>();
        jcbRazaMadre = new javax.swing.JComboBox<>();
        jcbSexo = new javax.swing.JComboBox<>();
        jcbEstado = new javax.swing.JComboBox<>();
        jcbRazaPadre = new javax.swing.JComboBox<>();
        jcbX = new javax.swing.JLabel();
        jblRazasConforman = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jblMensajeNombre = new javax.swing.JLabel();
        jblMensajeFecha = new javax.swing.JLabel();
        jblMensajeRazas = new javax.swing.JLabel();
        jblMensajeSexo = new javax.swing.JLabel();
        jblMensajeEstadoProduccion = new javax.swing.JLabel();
        txtNumeroIdentificador = new javax.swing.JTextField();
        jblDatosObligatorios = new javax.swing.JLabel();
        jblDatosOpcionales = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        background.setBackground(new java.awt.Color(255, 255, 255));

        panelSideBar1.setBackground(new java.awt.Color(35, 52, 78));
        panelSideBar1.setForeground(new java.awt.Color(46, 125, 50));
        panelSideBar1.setPreferredSize(new java.awt.Dimension(270, 892));

        btnFinanzas.setBackground(new java.awt.Color(55, 72, 95));
        btnFinanzas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFinanzas.setForeground(new java.awt.Color(255, 255, 255));
        btnFinanzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-precios-32.png"))); // NOI18N
        btnFinanzas.setText("Finanzas");
        btnFinanzas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnFinanzas.setBorderPainted(false);
        btnFinanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinanzas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas.setIconTextGap(15);

        btnClientes.setBackground(new java.awt.Color(55, 72, 95));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-toro-32.png"))); // NOI18N
        btnClientes.setText("Registro de crias");
        btnClientes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnClientes.setBorderPainted(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.setIconTextGap(15);

        btnProduccion.setBackground(new java.awt.Color(55, 72, 95));
        btnProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-registro-32 (1).png"))); // NOI18N
        btnProduccion.setText("Registro productivo");
        btnProduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProduccion.setBorderPainted(false);
        btnProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProduccion.setIconTextGap(15);

        btnRegistrarGanado.setBackground(new java.awt.Color(55, 72, 95));
        btnRegistrarGanado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarGanado.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32 (1).png"))); // NOI18N
        btnRegistrarGanado.setText("Registrar ganado");
        btnRegistrarGanado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnRegistrarGanado.setBorderPainted(false);
        btnRegistrarGanado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarGanado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarGanado.setIconTextGap(15);

        lblTituloSideBar.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTituloSideBar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSideBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-vaca-70.png"))); // NOI18N
        lblTituloSideBar.setText("Ganado");
        lblTituloSideBar.setIconTextGap(20);

        panelLinea.setBackground(new java.awt.Color(245, 245, 245));
        panelLinea.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout panelLineaLayout = new javax.swing.GroupLayout(panelLinea);
        panelLinea.setLayout(panelLineaLayout);
        panelLineaLayout.setHorizontalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelLineaLayout.setVerticalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btnHistorialSanitario.setBackground(new java.awt.Color(55, 72, 95));
        btnHistorialSanitario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistorialSanitario.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialSanitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-vacuna-32.png"))); // NOI18N
        btnHistorialSanitario.setText("Historial sanitario");
        btnHistorialSanitario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnHistorialSanitario.setBorderPainted(false);
        btnHistorialSanitario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialSanitario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistorialSanitario.setIconTextGap(15);

        btnReportes.setBackground(new java.awt.Color(55, 72, 95));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-gráfico-de-barras-32.png"))); // NOI18N
        btnReportes.setText("Historial productivo");
        btnReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnReportes.setBorderPainted(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.setIconTextGap(15);

        javax.swing.GroupLayout panelSideBar1Layout = new javax.swing.GroupLayout(panelSideBar1);
        panelSideBar1.setLayout(panelSideBar1Layout);
        panelSideBar1Layout.setHorizontalGroup(
            panelSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnHistorialSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelSideBar1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelSideBar1Layout.setVerticalGroup(
            panelSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBar1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTituloSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnRegistrarGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHistorialSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRegistrarGanado.setBackground(new java.awt.Color(255, 255, 255));

        jblTituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblTituloPanel.setForeground(new java.awt.Color(0, 0, 0));
        jblTituloPanel.setText("Registro de ganado");

        txtPeso.setBackground(new java.awt.Color(255, 255, 255));
        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(0, 0, 0));
        txtPeso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Peso (kg) ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        txtPeso.setCaretColor(new java.awt.Color(0, 0, 0));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nombre del animal ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNombre.setCaretColor(new java.awt.Color(0, 0, 0));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jblFechaNacimiento.setBackground(new java.awt.Color(0, 0, 0));
        jblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        jblFechaNacimiento.setText("Fecha de nacimiento");

        jcbMes.setBackground(new java.awt.Color(255, 255, 255));
        jcbMes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbMes.setForeground(new java.awt.Color(0, 0, 0));
        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Noviembree", "Febrero ", "Marzo", "Abril", "Mayo", "Junio", "julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbMes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jcbDia.setBackground(new java.awt.Color(255, 255, 255));
        jcbDia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbDia.setForeground(new java.awt.Color(0, 0, 0));
        jcbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "55", "34", "23", "12" }));
        jcbDia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Día", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jcbRazaMadre.setBackground(new java.awt.Color(255, 255, 255));
        jcbRazaMadre.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbRazaMadre.setForeground(new java.awt.Color(0, 0, 0));
        jcbRazaMadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "raza 2", "Holstein", "Jersey", "Pardo Suizo", "Brahman", "Angus", "Charolais", "Gyr", "Girolando", "Normando", "Simmental", "Ayrshire" }));
        jcbRazaMadre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Raza madre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jcbSexo.setBackground(new java.awt.Color(255, 255, 255));
        jcbSexo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbSexo.setForeground(new java.awt.Color(0, 0, 0));
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sexo", "Macho", "Hembra" }));
        jcbSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jcbEstado.setBackground(new java.awt.Color(255, 255, 255));
        jcbEstado.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(0, 0, 0));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Produciendo", "Enfermo", "Vendido", "Muerto" }));
        jcbEstado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jcbRazaPadre.setBackground(new java.awt.Color(255, 255, 255));
        jcbRazaPadre.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbRazaPadre.setForeground(new java.awt.Color(0, 0, 0));
        jcbRazaPadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "raza 1", "Holstein", "Jersey", "Pardo Suizo", "Brahman", "Angus", "Charolais", "Gyr", "Girolando", "Normando", "Simmental", "Ayrshire" }));
        jcbRazaPadre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Raza padre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jcbX.setBackground(new java.awt.Color(255, 255, 255));
        jcbX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcbX.setForeground(new java.awt.Color(0, 0, 0));
        jcbX.setText("X");

        jblRazasConforman.setBackground(new java.awt.Color(0, 0, 0));
        jblRazasConforman.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblRazasConforman.setForeground(new java.awt.Color(0, 0, 0));
        jblRazasConforman.setText("Razas que lo conforman");

        btnRegistrar.setBackground(new java.awt.Color(49, 72, 110));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jblMensajeNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeNombre.setForeground(new java.awt.Color(204, 0, 51));
        jblMensajeNombre.setText("Ingresa un nombre");

        jblMensajeFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeFecha.setForeground(new java.awt.Color(204, 0, 51));
        jblMensajeFecha.setText("Ingresa un fecha");

        jblMensajeRazas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeRazas.setForeground(new java.awt.Color(204, 0, 51));
        jblMensajeRazas.setText("Ingresa una raza");

        jblMensajeSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeSexo.setForeground(new java.awt.Color(204, 0, 51));
        jblMensajeSexo.setText("Ingresas un sexo");

        jblMensajeEstadoProduccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeEstadoProduccion.setForeground(new java.awt.Color(204, 0, 51));
        jblMensajeEstadoProduccion.setText("Selecciona un estado de produccion");

        txtNumeroIdentificador.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroIdentificador.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtNumeroIdentificador.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroIdentificador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Numero identificador ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumeroIdentificador.setCaretColor(new java.awt.Color(0, 0, 0));

        jblDatosObligatorios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDatosObligatorios.setForeground(new java.awt.Color(0, 0, 0));
        jblDatosObligatorios.setText("Datos obligatorios");

        jblDatosOpcionales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDatosOpcionales.setForeground(new java.awt.Color(0, 0, 0));
        jblDatosOpcionales.setText("Datos opcionales");

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Descripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        txtDescripcion.setCaretColor(new java.awt.Color(0, 0, 0));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));

        javax.swing.GroupLayout panelRegistrarGanadoLayout = new javax.swing.GroupLayout(panelRegistrarGanado);
        panelRegistrarGanado.setLayout(panelRegistrarGanadoLayout);
        panelRegistrarGanadoLayout.setHorizontalGroup(
            panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarGanadoLayout.createSequentialGroup()
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblTituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbMes, 0, 100, Short.MAX_VALUE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jcbDia, 0, 97, Short.MAX_VALUE)))
                                .addGap(125, 125, 125))))
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblRazasConforman, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblMensajeSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblMensajeEstadoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarGanadoLayout.createSequentialGroup()
                            .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarGanadoLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jcbRazaPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcbX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarGanadoLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jcbRazaMadre, 0, 1, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarGanadoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jblMensajeRazas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jblMensajeFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblMensajeNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jblDatosObligatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(125, 125, 125)))
                .addGap(46, 46, 46)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblDatosOpcionales, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtNumeroIdentificador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                        .addGap(56, 56, 56)))
                .addGap(38, 38, 38))
            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegistrarGanadoLayout.setVerticalGroup(
            panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jblTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblDatosObligatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblDatosOpcionales, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblMensajeNombre)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jblFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblMensajeFecha)
                        .addGap(18, 18, 18)
                        .addComponent(jblRazasConforman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbRazaPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbRazaMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblMensajeRazas)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblMensajeSexo)
                        .addGap(18, 18, 18)
                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jblMensajeEstadoProduccion))
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(panelRegistrarGanado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistrarGanado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSideBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFinanzas;
    private javax.swing.JButton btnHistorialSanitario;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarGanado;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jblDatosObligatorios;
    private javax.swing.JLabel jblDatosOpcionales;
    private javax.swing.JLabel jblFechaNacimiento;
    private javax.swing.JLabel jblMensajeEstadoProduccion;
    private javax.swing.JLabel jblMensajeFecha;
    private javax.swing.JLabel jblMensajeNombre;
    private javax.swing.JLabel jblMensajeRazas;
    private javax.swing.JLabel jblMensajeSexo;
    private javax.swing.JLabel jblRazasConforman;
    private javax.swing.JLabel jblTituloPanel;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbRazaMadre;
    private javax.swing.JComboBox<String> jcbRazaPadre;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JLabel jcbX;
    private javax.swing.JLabel lblTituloSideBar;
    private javax.swing.JPanel panelLinea;
    private javax.swing.JPanel panelRegistrarGanado;
    private javax.swing.JPanel panelSideBar1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroIdentificador;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
