/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Brayan C
 */
public class PanelCrearCuenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelCrearCuenta
     */
    public PanelCrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelIniciarSesion = new javax.swing.JPanel();
        lblCrearCuenta = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jblCorreo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombres = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jblUsuario = new javax.swing.JLabel();
        jblNombreFinca = new javax.swing.JLabel();
        jblUbicacion = new javax.swing.JLabel();
        jbllContraseña = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombreFinca = new javax.swing.JTextField();
        jpfContraseña = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtVereda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mensajeNombres = new javax.swing.JLabel();
        mensajeUsuario = new javax.swing.JLabel();
        mensajeContraseña = new javax.swing.JLabel();
        mensajeCorreo = new javax.swing.JLabel();
        mensajeNombreDeLaFinca = new javax.swing.JLabel();
        mensajeUbicacion = new javax.swing.JLabel();
        jcbDepartamento = new javax.swing.JComboBox<>();
        jcbMunicipio = new javax.swing.JComboBox<>();

        background.setBackground(new java.awt.Color(255, 255, 255));

        panelIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        panelIniciarSesion.setForeground(new java.awt.Color(245, 255, 255));

        lblCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblCrearCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblCrearCuenta.setText("Crear una cuenta");

        lblNombres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(0, 0, 0));
        lblNombres.setText("Nombres y apellidos");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        jblCorreo.setText("Corrreo electrónico");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombres.setText("Nombres y apellidos");
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(0, 0, 0));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.setText("Nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setCaretColor(new java.awt.Color(0, 0, 0));

        jblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jblUsuario.setText("Nombre de usuario");

        jblNombreFinca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNombreFinca.setForeground(new java.awt.Color(0, 0, 0));
        jblNombreFinca.setText("Nombre de la finca");

        jblUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        jblUbicacion.setText("Ubicación");

        jbllContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbllContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jbllContraseña.setText("Contraseña");

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreo.setText("Correo electrónico");
        txtCorreo.setBorder(null);
        txtCorreo.setCaretColor(new java.awt.Color(0, 0, 0));

        txtNombreFinca.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreFinca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreFinca.setText("Nombre de la finca");
        txtNombreFinca.setBorder(null);
        txtNombreFinca.setCaretColor(new java.awt.Color(0, 0, 0));

        jpfContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jpfContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpfContraseña.setText("**************");
        jpfContraseña.setBorder(null);
        jpfContraseña.setCaretColor(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        txtVereda.setBackground(new java.awt.Color(255, 255, 255));
        txtVereda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVereda.setForeground(new java.awt.Color(153, 153, 153));
        txtVereda.setText("Vereda");
        txtVereda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vereda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtVereda.setCaretColor(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));

        mensajeNombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeNombres.setForeground(new java.awt.Color(204, 0, 0));

        mensajeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeUsuario.setForeground(new java.awt.Color(204, 0, 0));

        mensajeContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeContraseña.setForeground(new java.awt.Color(204, 0, 0));

        mensajeCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeCorreo.setForeground(new java.awt.Color(204, 0, 0));

        mensajeNombreDeLaFinca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeNombreDeLaFinca.setForeground(new java.awt.Color(204, 0, 0));

        mensajeUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeUbicacion.setForeground(new java.awt.Color(204, 0, 0));

        jcbDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
        jcbDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jcbMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipio" }));
        jcbMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombreFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeNombreDeLaFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                        .addComponent(jcbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jcbMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mensajeUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbllContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblNombres)
                .addGap(12, 12, 12)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(mensajeNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jblUsuario)
                .addGap(12, 12, 12)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(mensajeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jblCorreo)
                .addGap(12, 12, 12)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mensajeCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jblNombreFinca)
                .addGap(1, 1, 1)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtNombreFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(mensajeNombreDeLaFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jblUbicacion)
                .addGap(12, 12, 12)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(mensajeUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jbllContraseña)
                .addGap(12, 12, 12)
                .addComponent(jpfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mensajeContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addComponent(panelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPasswordField getJpfContraseña() {
        return jpfContraseña;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JTextField getTxtNombreFinca() {
        return txtNombreFinca;
    }

    public JTextField getTxtNombres() {
        return txtNombres;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public JTextField getTxtVereda() {
        return txtVereda;
    }

    public String getCorreo() {
        String correo = txtCorreo.getText();
        return (verificarCamposDeTexto(correo, "Correo electrónico")) ? correo.trim() : null;
    }

    public String getNombreFinca() {
        String nombreDeLaFinca = txtNombreFinca.getText();
        return (verificarCamposDeTexto(nombreDeLaFinca, "Nombre de la finca")) ? nombreDeLaFinca.trim() : null;
    }

    public String getNombres() {
        String nombres = txtNombres.getText();
        return (verificarCamposDeTexto(nombres, "Nombres y apellidos")) ? nombres.trim() : null;
    }

    public String getUsuario() {
        String usuario = txtUsuario.getText();
        return (verificarCamposDeTexto(usuario, "Nombre de usuario")) ? usuario.trim() : null;
    }

    public String getContraseña() {
        String contraseña = String.valueOf(jpfContraseña.getPassword());
        return (verificarCamposDeTexto(contraseña, "**************")) ? contraseña.trim() : null;
    }

    public String getVereda() {
        String vereda = txtVereda.getText();
        return (verificarCamposDeTexto(vereda, "Vereda")) ? vereda.trim() : null;
    }
    
    public JComboBox<String> getJcbDepartamento() {
        return jcbDepartamento;
    }

    public JComboBox<String> getJcbMunicipio() {
        return jcbMunicipio;
    }

    public void setJcbDepartamento(JComboBox<String> jcbDepartamento) {
        this.jcbDepartamento = jcbDepartamento;
    }

    public void setJcbMunicipio(JComboBox<String> jcbMunicipio) {
        this.jcbMunicipio = jcbMunicipio;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }
    
    private boolean verificarCamposDeTexto(String campoDeTexto, String campoAValidar) {
        return campoDeTexto != null && !campoDeTexto.trim().isEmpty() && !campoDeTexto.trim().equals(campoAValidar);
    }

    public void setJpfContraseña(String texto) {
        this.jpfContraseña.setText(texto);
    }

    public void setTxtCorreo(String texto) {
        this.txtCorreo.setText(texto);
    }

    public void setTxtNombreFinca(String texto) {
        this.txtNombreFinca.setText(texto);
    }

    public void setTxtNombres(String texto) {
        this.txtNombres.setText(texto);
    }

    public void setTxtUsuario(String texto) {
        this.txtUsuario.setText(texto);
    }

    public void setTxtVereda(String texto) {
        this.txtVereda.setText(texto);
    }

    public void setMensajeContraseña(String mensajeContraseña) {
        this.mensajeContraseña.setText(mensajeContraseña);
    }

    public void setMensajeCorreo(String mensajeCorreo) {
        this.mensajeCorreo.setText(mensajeCorreo);
    }

    public void setMensajeNombreDeLaFinca(String mensajeNombreDeLaFinca) {
        this.mensajeNombreDeLaFinca.setText(mensajeNombreDeLaFinca);
    }

    public void setMensajeNombres(String mensajeNombres) {
        this.mensajeNombres.setText(mensajeNombres);
    }

    public void setMensajeUbicacion(String mensajeUbicacion) {
        this.mensajeUbicacion.setText(mensajeUbicacion);
    }

    public void setMensajeUsuario(String mensajeUsuario) {
        this.mensajeUsuario.setText(mensajeUsuario);
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jblCorreo;
    private javax.swing.JLabel jblNombreFinca;
    private javax.swing.JLabel jblUbicacion;
    private javax.swing.JLabel jblUsuario;
    private javax.swing.JLabel jbllContraseña;
    private javax.swing.JComboBox<String> jcbDepartamento;
    private javax.swing.JComboBox<String> jcbMunicipio;
    private javax.swing.JPasswordField jpfContraseña;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel mensajeContraseña;
    private javax.swing.JLabel mensajeCorreo;
    private javax.swing.JLabel mensajeNombreDeLaFinca;
    private javax.swing.JLabel mensajeNombres;
    private javax.swing.JLabel mensajeUbicacion;
    private javax.swing.JLabel mensajeUsuario;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreFinca;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtVereda;
    // End of variables declaration//GEN-END:variables
}
