/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Brayan C
 */
public class PanelIniciarSesion extends javax.swing.JPanel {

    /**
     * Creates new form PanelIniciarSesion
     */
    public PanelIniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIniciarSesion = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jpfContraseña = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        mensajeContraseña = new javax.swing.JLabel();
        mensajeUsuario = new javax.swing.JLabel();

        panelIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        panelIniciarSesion.setForeground(new java.awt.Color(245, 255, 255));
        panelIniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("INICIAR SESIÓN");
        panelIniciarSesion.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 256, 55));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("USUARIO");
        panelIniciarSesion.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 315, 107, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panelIniciarSesion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 411, 542, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONTRASEÑA");
        panelIniciarSesion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 481, 140, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panelIniciarSesion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 575, 542, 10));

        jpfContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jpfContraseña.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jpfContraseña.setText("**************");
        jpfContraseña.setBorder(null);
        panelIniciarSesion.add(jpfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 536, 542, 33));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        panelIniciarSesion.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 542, 35));

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(0, 0, 0));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/silhouette-black-cow-head-logo-design-graphic-symbol-icon-illustration-creative-idea-vector (1).jpg"))); // NOI18N
        lblLogo.setText("MilkSys");
        panelIniciarSesion.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 197, -1));

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelIniciarSesion.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 685, 240, 70));

        mensajeContraseña.setBackground(new java.awt.Color(255, 255, 255));
        mensajeContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeContraseña.setForeground(new java.awt.Color(204, 0, 0));
        panelIniciarSesion.add(mensajeContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 540, 20));

        mensajeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        mensajeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeUsuario.setForeground(new java.awt.Color(204, 0, 0));
        panelIniciarSesion.add(mensajeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 540, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnEntrar() {
        return btnEntrar;
    }

    public String getContraseña() {
        String contraseña = String.valueOf(jpfContraseña.getPassword());
        return (verificarDatos(contraseña, "**************")) ? contraseña : null;
    }

    public String getUsuario() {
        String usuario = txtUsuario.getText();
        return (verificarDatos(usuario, "Ingrese su nombre de usuario")) ? usuario : null;
    }
    
    private boolean verificarDatos(String texto, String mensaje) {
        return texto != null && !texto.trim().isEmpty() && !texto.trim().equals(mensaje);
    }

    public JPasswordField getJpfContraseña() {
        return jpfContraseña;
    }

    public void setJpfContraseña(String jpfContraseña) {
        this.jpfContraseña.setText(jpfContraseña);
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(String txtUsuario) {
        this.txtUsuario.setText(txtUsuario);
    }

    public void setMensajeContraseña(String mensajeContraseña) {
        this.mensajeContraseña.setText(mensajeContraseña);
    }

    public void setMensajeUsuario(String mensajeUsuario) {
        this.mensajeUsuario.setText(mensajeUsuario);
    }
    
    

    
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jpfContraseña;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel mensajeContraseña;
    private javax.swing.JLabel mensajeUsuario;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
