/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author Brayan C
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaAutenticacion
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bacgraund = new javax.swing.JPanel();
        panelSideBar = new javax.swing.JPanel();
        btnFinanzas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        lblTituloSideBar = new javax.swing.JLabel();
        panelLinea = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUltimosRegistros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        lblTituloLitrosHoy = new javax.swing.JLabel();
        lblLitrosHoy = new javax.swing.JLabel();
        lblTituloPromedioMes = new javax.swing.JLabel();
        lblTituloMayorProduccion = new javax.swing.JLabel();
        lblTituloMenorProduccion = new javax.swing.JLabel();
        lblPromedioMes = new javax.swing.JLabel();
        lblMayorProduccion = new javax.swing.JLabel();
        lblMenorProduccion = new javax.swing.JLabel();
        lblTituloUltimosRegistros = new javax.swing.JLabel();
        lblTituloClientes = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bacgraund.setBackground(new java.awt.Color(245, 245, 245));

        panelSideBar.setBackground(new java.awt.Color(27, 37, 55));
        panelSideBar.setForeground(new java.awt.Color(46, 125, 50));
        panelSideBar.setPreferredSize(new java.awt.Dimension(270, 892));

        btnFinanzas.setBackground(new java.awt.Color(39, 51, 69));
        btnFinanzas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFinanzas.setForeground(new java.awt.Color(255, 255, 255));
        btnFinanzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-precios-32.png"))); // NOI18N
        btnFinanzas.setText("Finanzas");
        btnFinanzas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnFinanzas.setBorderPainted(false);
        btnFinanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinanzas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas.setIconTextGap(15);

        btnClientes.setBackground(new java.awt.Color(39, 51, 69));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-clientes-32.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnClientes.setBorderPainted(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.setIconTextGap(15);

        btnProduccion.setBackground(new java.awt.Color(39, 51, 69));
        btnProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-registro-32 (1).png"))); // NOI18N
        btnProduccion.setText("Producción");
        btnProduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProduccion.setBorderPainted(false);
        btnProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProduccion.setIconTextGap(15);

        btnInicio.setBackground(new java.awt.Color(39, 51, 69));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-casa-32.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnInicio.setBorderPainted(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setIconTextGap(15);

        lblTituloSideBar.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTituloSideBar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSideBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSideBar.setText("MilkSys");

        panelLinea.setBackground(new java.awt.Color(245, 245, 245));
        panelLinea.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout panelLineaLayout = new javax.swing.GroupLayout(panelLinea);
        panelLinea.setLayout(panelLineaLayout);
        panelLineaLayout.setHorizontalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLineaLayout.setVerticalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        btnSalir.setBackground(new java.awt.Color(39, 51, 69));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-salida-de-emergencia-32.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setIconTextGap(15);

        javax.swing.GroupLayout panelSideBarLayout = new javax.swing.GroupLayout(panelSideBar);
        panelSideBar.setLayout(panelSideBarLayout);
        panelSideBarLayout.setHorizontalGroup(
            panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFinanzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTituloSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSideBarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSideBarLayout.setVerticalGroup(
            panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBarLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTituloSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        panelHeader.setBackground(new java.awt.Color(97, 120, 148));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Hoy es martes 5 de mayo de 2025");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-usuario-30.png"))); // NOI18N
        lblUsuario.setText(" Brayan C");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelInicio.setBackground(new java.awt.Color(245, 245, 245));

        tablaUltimosRegistros.setForeground(new java.awt.Color(255, 255, 255));
        tablaUltimosRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Litros", "Cliente"
            }
        ));
        tablaUltimosRegistros.setPreferredSize(new java.awt.Dimension(580, 80));
        jScrollPane1.setViewportView(tablaUltimosRegistros);

        tablaClientes.setForeground(new java.awt.Color(255, 255, 255));
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "Precio/L", "Litros comprados"
            }
        ));
        jScrollPane2.setViewportView(tablaClientes);

        lblTituloLitrosHoy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloLitrosHoy.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloLitrosHoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloLitrosHoy.setText("Litros hoy");
        lblTituloLitrosHoy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblLitrosHoy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLitrosHoy.setForeground(new java.awt.Color(0, 0, 0));
        lblLitrosHoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLitrosHoy.setText("56L");
        lblLitrosHoy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTituloPromedioMes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloPromedioMes.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloPromedioMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPromedioMes.setText("Promedio mes");
        lblTituloPromedioMes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTituloMayorProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloMayorProduccion.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloMayorProduccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMayorProduccion.setText("Mayor producción");
        lblTituloMayorProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTituloMenorProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloMenorProduccion.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloMenorProduccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMenorProduccion.setText("Menor produccion");
        lblTituloMenorProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPromedioMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPromedioMes.setForeground(new java.awt.Color(0, 0, 0));
        lblPromedioMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromedioMes.setText("30L");
        lblPromedioMes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMayorProduccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMayorProduccion.setForeground(new java.awt.Color(0, 0, 0));
        lblMayorProduccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMayorProduccion.setText("02/04/2025: 56L");
        lblMayorProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMenorProduccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMenorProduccion.setForeground(new java.awt.Color(0, 0, 0));
        lblMenorProduccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenorProduccion.setText("05/04/2025: 20L");
        lblMenorProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTituloUltimosRegistros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloUltimosRegistros.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloUltimosRegistros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloUltimosRegistros.setText("Ultimos registros");

        lblTituloClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloClientes.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloClientes.setText("Clientes");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloLitrosHoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLitrosHoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPromedioMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPromedioMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloMayorProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMayorProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenorProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloMenorProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addComponent(lblTituloUltimosRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(lblTituloClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloLitrosHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloPromedioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloMayorProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloMenorProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLitrosHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromedioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMayorProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenorProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloUltimosRegistros)
                    .addComponent(lblTituloClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        lblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenido.setText("Bienvenido!");

        javax.swing.GroupLayout bacgraundLayout = new javax.swing.GroupLayout(bacgraund);
        bacgraund.setLayout(bacgraundLayout);
        bacgraundLayout.setHorizontalGroup(
            bacgraundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bacgraundLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bacgraundLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panelSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(bacgraundLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bacgraundLayout.setVerticalGroup(
            bacgraundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bacgraundLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bacgraundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panelSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(bacgraundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bacgraund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bacgraund, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    public JPanel getPanel() {
        return panelSideBar;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bacgraund;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFinanzas;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLitrosHoy;
    private javax.swing.JLabel lblMayorProduccion;
    private javax.swing.JLabel lblMenorProduccion;
    private javax.swing.JLabel lblPromedioMes;
    private javax.swing.JLabel lblTituloClientes;
    private javax.swing.JLabel lblTituloLitrosHoy;
    private javax.swing.JLabel lblTituloMayorProduccion;
    private javax.swing.JLabel lblTituloMenorProduccion;
    private javax.swing.JLabel lblTituloPromedioMes;
    private javax.swing.JLabel lblTituloSideBar;
    private javax.swing.JLabel lblTituloUltimosRegistros;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelLinea;
    private javax.swing.JPanel panelSideBar;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaUltimosRegistros;
    // End of variables declaration//GEN-END:variables
}
